FROM python:3.11-slim

WORKDIR /app

# Copie des dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code source
COPY . .

# Exposition du port Streamlit
EXPOSE 8501

# Configuration Streamlit pour Docker
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

# Commande de lancement
CMD ["streamlit", "run", "frontend/app.py"]
